### ISSUE TITLE
Download到本地之后

### ISSUE THREAD

**Issue by MonFig** [tusenpo/FlappyFrog#18]
为什么会卡在历史的进程4%那里，，，，迷

**Comment by MonFig** [comment]
而且感觉长者撞管子的碰撞箱有点问题，碰撞判定有点错误，有时候明明可以擦边过的却没过过去。。。

**Comment by MonFig** [comment]
Mac的chrome和safari都没用。。。

**Comment by tusenpo** [comment]
第一个问题是因为浏览器默认不允许通过XHR访问本地文件
针对chrome浏览器，可以设置allow-file-access-from-files参数
在Mac OS X下的操作方法如下
先关闭chrome，然后打开终端(terminal)，输入 open /Applications/Google\ Chrome.app --args --allow-file-access-from-files ，回车

另一个办法是在本地搭建一个http server
比如 python -m SimpleHTTPServer  或者 npm install http-server
参考 https://github.com/lmccart/itp-creative-js/wiki/SimpleHTTPServer

**Comment by MonFig** [comment]
感谢回复！这个问题目前正考虑nginx来解决，不过很不幸我的电脑搭nginx好像也出了点问题。。。
