### ISSUE TITLE
下载到本地之后没有声音

### ISSUE THREAD

**Issue by kokoriolll** [tusenpo/FlappyFrog#21]
下到本地之后会卡到12%，之后我放到服务器上没有声音。

**Comment by tusenpo** [comment]
一定是你打开的姿势不对

**Comment by tusenpo** [comment]
下载到本地之后没有声音请参见#18
放到服务器上还是没有声音那一定是你的姿势不对了

**Comment by kokoriolll** [comment]
穿着红衣玩也不行吗？

**Comment by tusenpo** [comment]
按理说随便放到一个静态空间就可以玩，不该出现你说的这种情况，难道是网络不畅？
