### ISSUE TITLE
Excited!

### ISSUE THREAD

**Issue by xu1sec** [tusenpo/FlappyFrog#22]
Your game is very exciting, I zupport!

**Comment by tusenpo** [comment]
life.extend(1s)

**Comment by angry-toads** [comment]
Can you give me your G+ or E-mail?
_**It is necessary to discuss it personally**_

**Comment by tusenpo** [comment]
[G+](https://plus.google.com/113729061063515018628)1s

**Comment by angry-toads** [comment]
Hangouts invitation sent.
