### ISSUE TITLE
希望加入Safari缩略图图标和取消标题栏标记

### ISSUE THREAD

**Issue by megabitsenmzq** [tusenpo/FlappyFrog#24]
希望加入Safari缩略图图标
http://www.jianshu.com/p/ff35c7d016e2
和取消标题栏标记
<meta name="apple-mobile-web-app-capable" content="yes" />
这样可以让网页可以放在主屏幕上，看起来就像是个App

**Comment by tusenpo** [comment]
已加入缩略图图标，但是怎样取消标题栏标记？

**Comment by megabitsenmzq** [comment]
<meta name="apple-mobile-web-app-capable" content="yes" />

**Comment by megabitsenmzq** [comment]
网页里加一个<meta name="apple-mobile-web-app-capable" content="yes" />

**Comment by megabitsenmzq** [comment]
这网页下面有个隐藏用户栏那个，就那个加进去就行 http://weizhifeng.net/make-web-app-more-native.html

**Comment by megabitsenmzq** [comment]
刚看了一下，好像这样就已经可以隐藏各种栏了，可能是新版本的iOS该规矩了吧，OK那这样就可以了，这是坠好的！

**Comment by tusenpo** [comment]
吼啊

**Comment by tusenpo** [comment]
第一眼总是把native看成naive
