### ISSUE TITLE
请问有没有退出游戏后返回总时间的接口

### ISSUE THREAD

**Issue by Page-David** [tusenpo/FlappyFrog#27]
我把这个亦可赛艇的游戏写进了Flask框架里，我想做个有HOMEPAGE的主页，请问能不能在玩家退出时代码能够得到他玩的时间？

**Comment by Page-David** [comment]
https://github.com/Page-David/flappyfrog_flask_build/releases/tag/v1.0
蛤蛤，吼吗？

**Comment by tusenpo** [comment]
分数在 _score 这个变量里

**Comment by Page-David** [comment]
吼哇，谢谢！
