### ISSUE TITLE
自搭建服务器卡在96%

### ISSUE THREAD

**Issue by yalewoosoft** [tusenpo/FlappyFrog#28]
我用byethost免费空间，架设了FlappyFrog服务器，但部分设备加载进度卡在96%。网址: flappyfrog.ml

**Comment by beckno9** [comment]
Bytehost不吼哇
还是自己去买个VPS比较靠谱，可以去看看HostHatch，无视那个c，是蛤丝互联
Proudly using Microsoft Lumia 640. Powered by Windows 10 Mobile.

**Comment by yalewoosoft** [comment]
其实我已经有vps了，只是配置不好只能用来ss。所以96%只是与服务器配置有关？但现在的状况是，电脑100%ok，Android端50%，iOS全跪，所以我感觉我还是太naive。

Sent from my iPhone

On Aug 17, 2016, at 22:28, Beck <notifications@github.com<mailto:notifications@github.com>> wrote:

Bytehost不吼哇
还是自己去买个VPS比较靠谱，可以去看看HostHatch，无视那个c，是蛤丝互联
Proudly using Microsoft Lumia 640. Powered by Windows 10 Mobile.

―
