### ISSUE TITLE
有素材列表吗

### ISSUE THREAD

**Issue by twiceyuan** [tusenpo/FlappyFrog#38]
里面有一句话听不清，也不知道是哪里的，感觉还是要再学习一个

**Comment by twiceyuan** [comment]
https://tusenpo.github.io/FlappyFrog/sounds/score7.ogg 就是这个~

**Comment by Page-David** [comment]
好像是

> 闷声发大财

这句话剪过的。

**Comment by twiceyuan** [comment]
志己找到了，是「很惭愧」
一点微小的工作，谢谢大家
