### ISSUE TITLE
gameover之后，消失的生命值没有清零

### ISSUE THREAD

**Issue by lirenjie95** [tusenpo/FlappyFrog#7]
![screenshot_2016-03-23-14-04-07_com tencent mm](https://cloud.githubusercontent.com/assets/17038472/13977173/bdcdbdb8-f094-11e5-8d52-b22a81bd34c0.png)
如图，这个样子是不行的

**Comment by tusenpo** [comment]
就是这样设计的，是为了提醒你续命还需命来续

**Comment by tusenpo** [comment]
你本身也要判断，明白这意思吧？

**Comment by lirenjie95** [comment]
我还是要学习一个

**Comment by jwt625** [comment]
那建议restart后消失的生命值仍然不清零~ :neckbeard:
